DROP SCHEMA IF EXISTS NEURONALDATA;

CREATE SCHEMA NEURONALDATA;


USE NEURONALDATA;

DROP TABLE IF EXISTS HIDDENLAYER;

CREATE TABLE HIDDENLAYER(
SAVE_NR INTEGER AUTO_INCREMENT,
ERFOLGSRATE DOUBLE,
INPUT_NEURON INTEGER,
HIDDEN_NEURON_ONE INTEGER,
HIDDEN_NEURON_TWO INTEGER,
HIDDEN_NEURON_THREE INTEGER,
HIDDEN_NEURON_FOUR INTEGER,
HIDDEN_NEURON_FIVE INTEGER,

PRIMARY KEY (SAVE_NR)
);

DROP TABLE IF EXISTS HIDDENDATA;

CREATE TABLE HIDDENDATA(
SAVE_NR INTEGER,
LAYER_NR INTEGER,
KANTEN_NUMMER INTEGER,
PRE_NEURON_IDENT INTEGER,
NEXT_NEURON_IDENT INTEGER,
WEIGHT DOUBLE,

PRIMARY KEY (SAVE_NR, LAYER_NR, KANTEN_NUMMER)
);


