DROP SCHEMA IF EXISTS NEURONALDATA;

CREATE SCHEMA NEURONALDATA;


USE NEURONALDATA;

DROP TABLE IF EXISTS MAINTABLE;

CREATE TABLE MAINTABLE(
SAVE_NR INTEGER,
ACCURACY DOUBLE,
INPUT_NEURON INTEGER,
HIDDEN_NEURON_ONE INTEGER,
HIDDEN_NEURON_TWO INTEGER,
HIDDEN_NEURON_THREE INTEGER,
HIDDEN_NEURON_FOUR INTEGER,
HIDDEN_NEURON_FIVE INTEGER,
OUTPUT_NEURON INTEGER,

PRIMARY KEY (SAVE_NR)
);

DROP TABLE IF EXISTS EDGETABLE;

CREATE TABLE EDGETABLE(
SAVE_NR INTEGER,
LAYER_NR INTEGER,
EDGE_NR INTEGER,
PRE_NEURON_IDENT INTEGER,
NEXT_NEURON_IDENT INTEGER,
WEIGHT DOUBLE,

PRIMARY KEY (SAVE_NR, LAYER_NR, EDGE_NR)
);


