DROP SCHEMA IF EXISTS neuronaldata;

CREATE SCHEMA neuronaldata;


USE neuronaldata;

DROP TABLE IF EXISTS maintable;

CREATE TABLE maintable(
SAVE_NR INTEGER,
ACCURACY DOUBLE,
INPUT_NEURON INTEGER,
HIDDEN_NEURON_ONE INTEGER,
HIDDEN_NEURON_TWO INTEGER,
HIDDEN_NEURON_THREE INTEGER,
HIDDEN_NEURON_FOUR INTEGER,
HIDDEN_NEURON_FIVE INTEGER,
OUTPUT_NEURON INTEGER,

PRIMARY KEY (SAVE_NR)
);

DROP TABLE IF EXISTS edgetable;

CREATE TABLE edgetable(
SAVE_NR INTEGER,
LAYER_NR INTEGER,
EDGE_NR INTEGER,
PRE_NEURON_IDENT INTEGER,
NEXT_NEURON_IDENT INTEGER,
WEIGHT DOUBLE,

PRIMARY KEY (SAVE_NR, LAYER_NR, EDGE_NR)
);


